cli: switch to getopt
The compilation warning level has been lowered from 3 to 2 to avoid
a spurious warning message:

> ../rbh-sync.c: In function ‘main’:
> ../rbh-sync.c:371:9: error: ISO C forbids empty initializer braces [-Werror=pedantic]
>   371 |         {}
>       |         ^

Signed-off-by: Quentin Bouget <quentin.bouget@cea.fr>
Change-Id: Iecba93c2db52a17124a027cd049b9cee192e873d